version: '3'
services:
  ####################### Document Receiver Definition #######################
  document-receiver:
    build:
      context: ./jrcc-document-receiver
      args: 
        REDIS_HOST: redis
        REDIS_PORT: 6379
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
        RABBITMQ_USERNAME: guest
        RABBITMQ_PASSWORD: guest
    ports:
      - "5050:8080"
    networks:
      - justin-rcc
    depends_on: 
      - redis
      - rabbitmq

  ####################### REDIS SERVER ######################################
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    restart: always
    networks:
      - justin-rcc

  ####################### RABBITMQ SERVER ######################################
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
        - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - justin-rcc

  ####################### REDIS COMMANDER ######################################
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - justin-rcc

networks: 
  justin-rcc:
    driver: "bridge"

volumes:
  data-rabbit:
    external: false
  data-redis:
    external: false
