spring:
   application:
      name: document-receiver
   redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
   rabbitmq:
      host: ${RABBITMQ_HOST}
      port: ${RABBITMQ_PORT}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}
bcgov:
  access:
    input: http
    output:
      document-type: prosecution-report
      plugin: rabbitmq
      rabbitmq:
         ttl: 1
